# データベースへの接続設定（今回はメモリ上に一時的なDBを作ります）
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# アプリ起動時に、後述する「schema.sql」と「data.sql」を自動実行する設定
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# Renderから割り当てられるポートに自動追従する設定
server.port=${PORT:8080}
